/// Flutter icons HomeIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HomeIcons
///      fonts:
///       - asset: fonts/HomeIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class HomeIcons {
  HomeIcons._();

  static const _kFontFam = 'HomeIcons';
  static const String _kFontPkg = null;

  static const IconData ps_logo_of_games =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple__2_ =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData app__1_ =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData game_controller =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
